apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-node
          image: archinwater/testrepo:0.2
